MS-198: Psychologist interview details
BaSD-2021/Dami-MindSet-app pull request #102
Opened 2021-12-28 17:21 UTC by valeferaudo

2021-12-30 01:13 UTC, sofpag requested changes
Por algún motivo está rama esta rota en la parte del ADMIN (devolpment funciona bien)
![imagen](https://user-images.githubusercontent.com/90916077/147713957-2470fb0e-8697-4d0c-980e-f9657287b7da.png)

Intenté traerme el candidato con la entrevista realizada pero no tuve suerte. Desconfío en como está la ruta

2022-01-03 16:43 UTC, valeferaudo commented on src/Components/Psychologist/Interview/interview.module.css
> +}
i don´t understand the requested changes or where i have to

2022-01-04 14:56 UTC, AndresCespedes23 requested changes

2022-01-04 14:56 UTC, AndresCespedes23 commented on src/Components/Psychologist/Interview/index.js
> +  const interview = useSelector((state) => state.interviews.interview);
This should be **SESSION** because is between a psychologist and a postulant. 
Interviews are between a client and a postulant. It's a little bit tricky.

2022-01-04 14:56 UTC, AndresCespedes23 commented on src/Components/Psychologist/Interview/index.js
> +    dispatch(getOneInterview(id));
You want to GET the info of a **session**. I made the same mistake in the past

2022-01-04 23:56 UTC, sofpag approved these changes

2022-01-05 14:25 UTC, AndresCespedes23 approved these changes

2022-01-05 14:26 UTC, merged