MS-195: Psychologists first view after login
BaSD-2021/Dami-MindSet-app pull request #103
Opened 2021-12-28 20:32 UTC by BareaMartin

2021-12-28 21:52 UTC, AndresCespedes23 approved these changes

2021-12-28 22:12 UTC, julianv97 approved these changes

2021-12-28 22:12 UTC, julianv97 commented on src/Components/Psychologist/FirstView/first-view.module.css
> +.assignBtn {
missing cursor: pointer for the buttons

2021-12-28 22:12 UTC, julianv97 commented on src/Components/Psychologist/FirstView/index.js
> +                  return [
this returns should not be an array, you have tu use ()

2021-12-28 22:12 UTC, julianv97 commented on src/Components/Psychologist/FirstView/index.js
> +                  return [
same return here

2021-12-28 22:13 UTC, julianv97 requested changes
Le erré al botón de pedir cambios en la anterior

2021-12-29 14:28 UTC, julianv97 approved these changes

2021-12-29 14:28 UTC, merged