MS-241: Session details, Interview details.
BaSD-2021/Dami-MindSet-app pull request #135
Opened 2022-01-15 21:28 UTC by valeferaudo

2022-01-15 21:48 UTC, sofpag approved these changes

2022-01-15 21:48 UTC, sofpag commented on src/Components/Admin/Interviews/interviews.module.css
> +table {
acá

2022-01-15 21:48 UTC, sofpag commented on src/Components/Admin/Interviews/interviews.module.css
> +th{
acá

2022-01-15 21:48 UTC, sofpag commented on src/Components/Admin/Sessions/Session/session.module.css
> +  tr > td {
acá

2022-01-15 21:48 UTC, sofpag commented on src/Components/Admin/Sessions/sessions.module.css
> +table {
acá

2022-01-15 21:48 UTC, sofpag commented on src/Components/Admin/Sessions/sessions.module.css
> +th{
acá

2022-01-15 22:30 UTC, julianv97 requested changes
<img width="1070" alt="Screen Shot 2022-01-15 at 19 28 28" src="https://user-images.githubusercontent.com/72532469/149639634-e452d383-ad79-4ec0-a509-f259b4dcc70a.png">
we need to fix this styles, in sessions same
<img width="1062" alt="Screen Shot 2022-01-15 at 19 30 23" src="https://user-images.githubusercontent.com/72532469/149639656-292f2acf-cd14-4e1a-b749-6510a5ff8876.png">

2022-01-16 19:36 UTC, julianv97 approved these changes

2022-01-16 21:05 UTC, merged