MS-76: Applications - CRUD
BaSD-2021/Dami-MindSet-app pull request #15
Opened 2021-11-29 03:17 UTC by sofpag

Create, Read, Update, Delete the application resource

2021-11-29 04:35 UTC, julianv97 requested changes

2021-11-29 04:35 UTC, julianv97 commented on src/Components/Applications/index.js
> +    fetch('http://localhost:4000/api/applications')
this should be changed to an environment variable, this is repeated in others fetch.

2021-11-29 05:03 UTC, sofpag commented on src/Components/Applications/index.js
> +    fetch('http://localhost:4000/api/applications')
Oh! I was certain that i had changed all. Thanks you

2021-11-29 05:10 UTC, julianv97 approved these changes

2021-11-29 13:41 UTC, andrespienizzio approved these changes
Lo que me genera dudas es el tema del shared modal, porque de cambiar las propiedades lo haria en todos los modales

2021-11-29 16:58 UTC, damianalvarez requested changes

2021-11-29 16:58 UTC, damianalvarez commented on src/Components/Applications/Form/index.js
> +        return;
@sofpag Given that we are using the return here, we don't need the `else` sentence below

2021-11-29 16:58 UTC, damianalvarez commented on src/Components/Applications/Form/index.js
> +            return [
@sofpag let's use `return (` instead of returning an array of elements, remember that the render method needs only one element.

I say the same sentence in more than one case, I think that the search&replace feature from VSCode could help to replace all the cases

2021-11-29 16:58 UTC, damianalvarez commented on src/Components/Applications/index.js
> +      <div>
@sofpag Why are we wrapping the table in an empty div?

2021-11-29 16:58 UTC, damianalvarez commented on src/Components/Applications/index.js
> +                <tr key={application._id}>
@sofpag I think that we don't have this prop after adding a new application.

Take a look at what I'm getting after adding a new application.

![Screen Shot 2021-11-29 at 13 57 17](https://user-images.githubusercontent.com/9340490/143910364-041d6257-7f24-4756-8d9d-601151a8e1c1.png)


Look at this screenshot belowe, where I put some logs in order to see the response that is coming from the POST request
![Screen Shot 2021-11-29 at 13 54 59](https://user-images.githubusercontent.com/9340490/143910226-9bfb128f-2df1-45ae-8451-7451e585415d.png)

I think that this could be solved by adding the `_id` on the backend response.

2021-11-29 20:15 UTC, sofpag commented on src/Components/Applications/index.js
> +      <div>
I'm not sure, maybe I wanted to put some className and then changed my mind, but forgot to erase it

2021-11-29 23:24 UTC, sofpag commented on src/Components/Applications/index.js
> +                <tr key={application._id}>
I tried adding _id: newObjectId(), in the backend server, but it didn't work. 
Also, I changed the request to application.idPosition._id insted of application.idPosition.name (and so on) to test if it that request that was malfunctioning. But didn´t work either (I did a commit with this code). 
I did both changes alone and combining it. 
Juli and Valen think that a possible solution is to do another request to the server (if I undestood) 
I only came up with add an event that refresh the page, so it will not work well for a developer, but, for a user it will. 

PD: I put the "...loading..." because was the only way Valen and I came up with to show the date in that way (00-00-00) and that all keep working


![imagen](https://user-images.githubusercontent.com/90916077/143958233-267e2004-986d-4991-8151-730c5151cdd5.png)

2021-11-29 23:41 UTC, sofpag commented on src/Components/Applications/index.js
> +                <tr key={application._id}>
So, I don't know what we should do :/ 
This problem is common to all the resources that need another (like applications, interviews and sessions)

2021-11-30 00:11 UTC, sofpag commented on src/Components/Applications/index.js
> +                <tr key={application._id}>
Juli and Valen came up with the new fetch fn
```
fetch(`${process.env.REACT_APP_API}/applications/${response._id}`)
          .then((response) => response.json())
          .then((response) => setApplications([...applications, response]));
```
I did a new commit and push with de result 
![imagen](https://user-images.githubusercontent.com/90916077/143962173-e34d4364-277c-422f-a89b-64c8bcc9b500.png)
I (we) hope that the solution pleaced you :D

2021-11-30 02:47 UTC, damianalvarez requested changes

2021-11-30 02:47 UTC, damianalvarez commented on src/Components/Applications/index.js
> +    fetch(`${process.env.REACT_APP_API}/applications`)
@sofpag what do you think about creating a new function with this logic? In that case, we'll be able to reuse it when making the create, update and remove operations in order to get a fresh list after making those operations

```
  const getPositions = () => {
    fetch(`${process.env.REACT_APP_API}/applications`)
      .then((response) => {
        if (response.status === 200 || response.status === 201) return response.json();
        throw new Error(`HTTP ${response.status}`);
      })
      .then((response) => {
        setApplications(response);
      })
      .catch((err) => {
        setMessageType('error');
        setMessage('Error:', err);
      });
  };

  useEffect(() => {
    getPositions();
  }, []);

```

2021-11-30 02:47 UTC, damianalvarez commented on src/Components/Applications/index.js
> +    fetch(`${process.env.REACT_APP_API}/applications`)
cc @valeferaudo @julianv97

2021-11-30 02:47 UTC, damianalvarez commented on src/Components/Applications/index.js
> +        fetch(`${process.env.REACT_APP_API}/applications/${response._id}`)
@sofpag and here we can call the `getPositions()` function created above 🪄

2021-11-30 03:27 UTC, damianalvarez approved these changes

2021-11-30 03:27 UTC, merged