MS-75:  positions - crud
BaSD-2021/Dami-MindSet-app pull request #17
Opened 2021-11-29 16:21 UTC by VicenzoMantilla

2021-11-29 17:21 UTC, AlfonsoScornavacca approved these changes

2021-11-29 21:15 UTC, valeferaudo approved these changes

2021-11-29 23:09 UTC, damianalvarez requested changes

2021-11-29 23:09 UTC, damianalvarez commented on src/Components/Positions/Form/index.js
> +    fetch('http://localhost:4000/api/clients')
@VicenzoMantilla in order to make this PR work in another environment we need to use ENV variables instead of `http://localhost...`

2021-11-29 23:09 UTC, damianalvarez commented on src/Components/Positions/Form/index.js
> +    fetch('http://localhost:4000/api/profiles')
@VicenzoMantilla same thing here

2021-11-30 01:18 UTC, julianv97 commented on src/Components/Positions/Form/index.js
> +    fetch('http://localhost:4000/api/clients')
Done.

2021-11-30 01:18 UTC, julianv97 commented on src/Components/Positions/Form/index.js
> +    fetch('http://localhost:4000/api/profiles')
Done.

2021-11-30 03:23 UTC, damianalvarez approved these changes

2021-11-30 03:33 UTC, merged