Feature/ms 73/sessions crud
BaSD-2021/Dami-MindSet-app pull request #19
Opened 2021-11-29 18:41 UTC by palomaquiroz

2021-11-29 19:34 UTC, damianalvarez requested changes

2021-11-29 19:34 UTC, damianalvarez commented on src/Components/Sessions/Form/form.module.css
> +  }
@palomaquiroz indentation seems a bit off here

2021-11-29 19:34 UTC, damianalvarez commented on src/Components/Sessions/Form/form.module.css
> +  }
@palomaquiroz colors should be written using hex values. I saw the same thing in other components

2021-11-30 03:35 UTC, damianalvarez approved these changes

2021-12-01 12:45 UTC, VicenzoMantilla approved these changes

2021-12-01 20:56 UTC, merged