Feature/ms 72/clients crud
BaSD-2021/Dami-MindSet-app pull request #20
Opened 2021-11-29 20:18 UTC by AlfonsoScornavacca

2021-11-30 02:17 UTC, AndresCespedes23 approved these changes
Changes discussed via Discord

2021-11-30 03:29 UTC, damianalvarez requested changes

2021-11-30 03:29 UTC, damianalvarez commented on src/Components/Clients/Form/index.js
> +      fetch(`http://localhost:4000/api/clients/${id}`)
@AlfonsoScornavacca let's use env variables instead of `http://localhost:4000`

2021-11-30 03:30 UTC, damianalvarez submitted a review, later dismissed

2021-11-30 03:30 UTC, damianalvarez commented on src/Components/Clients/Form/form.module.css
> +.formField {
@AlfonsoScornavacca let's get rid of this file

2021-11-30 17:02 UTC, julianv97 requested changes

2021-11-30 17:02 UTC, julianv97 commented on src/Components/Shared/Modal/modal.module.css
> +  position: sticky;
this should be position:fixed;
so that you do not have the modal below the table.
![image](https://user-images.githubusercontent.com/72532469/144092958-4016bec8-8213-4928-a503-cf070cf5393b.png)

2021-12-01 14:44 UTC, julianv97 approved these changes

2021-12-01 20:31 UTC, merged