[FIX] MS-116: improve data loading
BaSD-2021/Dami-MindSet-app pull request #37
Opened 2021-12-03 19:01 UTC by AndresCespedes23

Everything is functional but there's a number of things to improve:

2021-12-03 22:05 UTC, julianv97 approved these changes

2021-12-03 23:30 UTC, julianv97 requested changes

2021-12-04 16:45 UTC, julianv97 approved these changes

2021-12-04 16:47 UTC, BareaMartin approved these changes
Tested locally, LGTM

2021-12-04 17:36 UTC, merged