MS-134: Clients implement redux
BaSD-2021/Dami-MindSet-app pull request #55
Opened 2021-12-10 14:02 UTC by valeferaudo

2021-12-12 22:19 UTC, sofpag requested changes

2021-12-12 22:19 UTC, sofpag commented on src/Components/Clients/Form/index.js
> +  // const client = useSelector((store) => store.clients.client);
Maybe you could delete those coments

2021-12-12 22:19 UTC, sofpag commented on src/Components/Clients/index.js
> +    console.log(id);
and delete this console.log too

2021-12-12 22:19 UTC, sofpag commented on src/redux/Clients/actions.js
> +import { SHOW_MESSAGE } from '../../constants/actionTypes';
you could do only one line of code here

2021-12-12 22:19 UTC, sofpag commented on src/redux/Clients/reducer.js
> +  client: null,
to me put  "null" cause me trouble, so I choose to put  an objet (" { } ") as I saw do Julián

2021-12-12 22:19 UTC, sofpag commented on src/redux/Clients/reducer.js
> +        // isLoading: true
you left many comments in this file

2021-12-12 22:19 UTC, sofpag commented on src/redux/Clients/thunks.js
> +  UPDATE_CLIENTS_FULFILLED,
this break the consistency, in the other files you import in this order: get, add, DELETE ...

2021-12-12 22:19 UTC, sofpag commented on src/redux/Clients/thunks.js
> +    fetch(BASE_URL)
as I said on Slack, i believe we could put more about the status error when we do the "fetch"

2021-12-12 22:22 UTC, sofpag commented
@valeferaudo The ADD didn´t work on herolu nor on local. 
This is in local 
![imagen](https://user-images.githubusercontent.com/90916077/145731832-121fa41d-ec89-4017-86b8-f06e24f066f3.png)
![imagen](https://user-images.githubusercontent.com/90916077/145731841-f6b4ed98-5e9a-40c2-b7d3-94c5d2431271.png)

Also GET_ONE is not working on local (but it is working on heroku)
![imagen](https://user-images.githubusercontent.com/90916077/145731863-8cedb7c7-7e5b-4a20-bf62-e106ebc33ab0.png)

So, I could not try the EDIT on local, but on heroku works

DELETE look fine

2021-12-13 19:34 UTC, BareaMartin approved these changes
Tested all on heroku deployment, looks good to me.

2021-12-13 19:55 UTC, sofpag approved these changes

2021-12-13 20:10 UTC, merged